### ISSUE TITLE
Unable to execute 'gcc-11': No such file or directory.

### ISSUE THREAD

**Issue by Ardvino** [LAVI-USP/pyDBT#1]
No clue what is wrong:

python setup.py install
running install
running bdist_egg
running egg_info
writing pyDBT.egg-info/PKG-INFO
writing dependency_links to pyDBT.egg-info/dependency_links.txt
writing requirements to pyDBT.egg-info/requires.txt
writing top-level names to pyDBT.egg-info/top_level.txt
reading manifest file 'pyDBT.egg-info/SOURCES.txt'
writing manifest file 'pyDBT.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_ext
building 'projectionDD' extension
creating build/temp.macosx-10.9-x86_64-3.8
creating build/temp.macosx-10.9-x86_64-3.8/pydbt
creating build/temp.macosx-10.9-x86_64-3.8/pydbt/sources
creating build/temp.macosx-10.9-x86_64-3.8/pydbt/sources/projectionDD
gcc-11 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/03arbj01/opt/anaconda3/include -arch x86_64 -I/Users/03arbj01/opt/anaconda3/include -arch x86_64 -I/Users/03arbj01/opt/anaconda3/include/python3.8 -c pydbt/sources/projectionDD/projectionDD.cpp -o build/temp.macosx-10.9-x86_64-3.8/pydbt/sources/projectionDD/projectionDD.o
unable to execute 'gcc-11': No such file or directory
error: command 'gcc-11' failed with exit status 1

**Comment by rodrigovimieiro** [comment]
Do you have gcc 11 installed? Run `gcc-11 --version`

**Comment by Ardvino** [comment]
I seem to not have it installed.

Can I contact you some way? I am very interested in this field of research. I am a high school student.

**Comment by rodrigovimieiro** [comment]
Run the command on the terminal:

`brew install gcc`

If you don't have brew, you can install it through:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
`

You will probably need Xcode:

`sudo xcode-select --install`

If you find any problems, you can contact me through my email, which is listed in the readme file. I can also send you the compiled files.

See these references: [[1](https://brew.sh)][[2](https://formulae.brew.sh/formula/gcc)][[3](https://developer.apple.com/forums/thread/652240)]

**Comment by Ardvino** [comment]
I have resolved the error now, by installing via Homebrew. Thank you for the help.
